// this is also known us model package so you can use either
package productscrud.products.crud.Entity;

import jakarta.persistence.*;
import lombok.Data;// it automatically creates getters and setters for you

@Entity// used to inform the compiler its an entity
@Table(name = "Product_inventory")
@Data
public class Product {
    // since in every table there is always an id column we have to make it autogenerated
    @Id// this is to specify the id as id in order to tell the compiler its an id
    @GeneratedValue(strategy = GenerationType.IDENTITY)// should be auto generated
    private long id;

    // we have several column and we have to specify each
    @Column (name = "Product_name", nullable = false)
    private String productName;// this is a column for the name of the product

    @Column(name = "color")
    private String color;

    @Column(name="price")
    private int price;
    @Column(name = "Name")
    private String name;

}
